-- =====================================================================
--  University Knowledge Network (UKN) — Demo Seed Data
--  Run AFTER database/schema.sql
--  MySQL 8.0.16+ · utf8mb4
-- =====================================================================
--
--  Seeds the four reference tables the rest of the system hangs off:
--      departments · skill_categories · skills · users
--
--  Every value is lifted from the existing frontend mock data so the
--  pages render identically once they start reading from MySQL:
--      admin/includes/taxonomy-data.php   -> departments, categories, skills
--      admin/includes/users-data.php      -> users (ids 1-16)
--      pages/skills/skill-details.php     -> skill descriptions + about copy
--      pages/network/skill-network.php    -> skills 11-14
--      pages/profile/*.php                -> bios, headlines, years
--
--  ------------------------------------------------------------------
--  PASSWORDS
--  ------------------------------------------------------------------
--  No plain-text password appears in this file. Every account gets the
--  SAME deliberately INVALID bcrypt-shaped placeholder: it is the right
--  length and character set, but it is not a hash of any password, so
--  password_verify() returns false for every input and NOBODY can log in
--  with the seed data as-is. That is intentional.
--
--  Before testing login, replace it with a real hash generated by
--  PHP's password_hash() using the PASSWORD_DEFAULT algorithm, then:
--      UPDATE users SET password_hash = '<the real hash>' WHERE id = 1;
--
--  ------------------------------------------------------------------
--  RECONCILED INCONSISTENCIES (see the backend preparation report)
--  ------------------------------------------------------------------
--  1. USER IDS. The frontend had three conflicting id namespaces
--     (admin/users-data.php, learner-profile.php, mentor-profile.php).
--     This seed adopts the ADMIN namespace as canonical: Nabila = 1,
--     Rahim = 2, Imran = 3, Hasan = 4, ... Every `&id=` link in
--     pages/ must be re-pointed to match.
--
--  2. NABILA RAHMAN'S ROLE. admin/users-data.php lists her as 'learner',
--     but index.php, the leaderboard and the right sidebar all treat her
--     as dual-role with 412 learning + 520 mentor points. Seeded as
--     'dual' — she is the demo account the whole role-switch flow needs.
--
--  3. DEPARTMENTS. The admin table had 5, the register/edit-profile
--     dropdowns had 7. Seeded with the superset of 7; the 5 admin ones
--     keep their established codes.
--
--  4. SKILLS. skills.php had 10, admin had 13 (no id 13), skill-network
--     had 14. Seeded with the full 14 so the network graph resolves every
--     node. Ids 1-10 match skills.php exactly.
--
--  5. CACHED AGGREGATES on users (points, ratings, session counts) are
--     copied from what the frontend currently displays. Once the
--     transactional tables are seeded, recompute them from
--     point_transactions / session_ratings / mentoring_sessions rather
--     than trusting these values.
-- =====================================================================

SET NAMES utf8mb4;

START TRANSACTION;

-- Invalid-by-design placeholder: bcrypt-shaped, matches no password.
SET @pw := '$2y$10$UknDemoSeedPlaceholderHashNotUsableForLogin0000000000';


-- =====================================================================
--  departments
--  (id, name, code, status, created_at)
-- =====================================================================
INSERT INTO departments (id, name, code, status, created_at) VALUES
(1, 'Computer Science',        'CSE',  'active', '2025-01-05 09:00:00'),
(2, 'Electrical Engineering',  'EEE',  'active', '2025-01-05 09:00:00'),
(3, 'Business Administration', 'BBA',  'active', '2025-01-05 09:00:00'),
(4, 'English',                 'ENG',  'active', '2025-01-05 09:00:00'),
(5, 'Economics',               'ECO',  'active', '2025-01-05 09:00:00'),
(6, 'Civil Engineering',       'CE',   'active', '2025-01-05 09:00:00'),
(7, 'Architecture',            'ARCH', 'active', '2025-01-05 09:00:00');


-- =====================================================================
--  skill_categories
--  (id, name, description, status, updated_at)
--  updated_at values match admin/skill-categories.php's "Last Updated".
-- =====================================================================
INSERT INTO skill_categories (id, name, description, status, created_at, updated_at) VALUES
(1, 'Programming',   'Programming languages and software development skills.',        'active', '2025-01-05 09:00:00', '2026-09-10 09:00:00'),
(2, 'Data',          'Database, analytics and data-focused skills.',                  'active', '2025-01-05 09:00:00', '2026-09-09 09:00:00'),
(3, 'Design',        'Interface, experience and visual design skills.',               'active', '2025-01-05 09:00:00', '2026-08-28 09:00:00'),
(4, 'Engineering',   'Hardware, electronics and applied engineering skills.',         'active', '2025-01-05 09:00:00', '2026-08-20 09:00:00'),
(5, 'Communication', 'Speaking, presenting and interpersonal communication skills.',  'active', '2025-01-05 09:00:00', '2026-09-01 09:00:00'),
(6, 'Academic',      'Academic research and writing skills.',                         'active', '2025-01-05 09:00:00', '2026-08-15 09:00:00'),
(7, 'Business',      'Marketing, strategy and business-facing skills.',               'active', '2025-01-05 09:00:00', '2026-08-12 09:00:00');


-- =====================================================================
--  skills
--  (id, name, slug, category_id, description, about, status, updated_at)
--
--  Ids 1-10  : pages/skills/skills.php + skill-details.php (with `about`)
--  Ids 11-14 : pages/network/skill-network.php graph nodes
-- =====================================================================
INSERT INTO skills (id, name, slug, category_id, description, about, status, created_at, updated_at) VALUES
(1, 'Python', 'python', 1,
 'A versatile programming language used for software development, automation, data analysis and machine learning.',
 'Python is the most taught skill on the network. Mentors cover everything from first syntax to pandas, scripting and the machine-learning coursework sequence, and most sessions run 45-60 minutes in the Student Union study rooms or online.',
 'active', '2025-01-05 09:00:00', '2026-09-12 09:00:00'),

(2, 'MySQL', 'mysql', 2,
 'A widely used relational database system for storing and querying structured data.',
 'Sessions typically start from writing and querying tables, then move into joins, indexes and the normalization rules that show up most in coursework and interviews.',
 'active', '2025-01-05 09:00:00', '2026-09-10 09:00:00'),

(3, 'React', 'react', 1,
 'A JavaScript library for building interactive user interfaces and single-page applications.',
 'Most mentors assume basic JavaScript and focus on components, state and the mistakes that trip up a first real project - prop drilling, effect dependencies and re-render loops.',
 'active', '2025-01-05 09:00:00', '2026-09-08 09:00:00'),

(4, 'UI/UX Design', 'ui-ux-design', 3,
 'Designing interfaces and experiences that are functional, accessible and easy to use.',
 'Sessions mix short critique of your own screens with the fundamentals - layout, hierarchy, contrast and how to justify a design decision, not just make one.',
 'active', '2025-01-05 09:00:00', '2026-09-06 09:00:00'),

(5, 'Data Analysis', 'data-analysis', 2,
 'Turning raw data into insight using spreadsheets, Python and statistical thinking.',
 'Mentors work through a real dataset with you - cleaning it, asking useful questions of it, and presenting what you found, rather than teaching statistics in the abstract.',
 'active', '2025-01-05 09:00:00', '2026-09-11 09:00:00'),

(6, 'Public Speaking', 'public-speaking', 5,
 'Structuring and delivering talks and presentations with confidence.',
 'Sessions are mostly practice: structuring a short talk, handling nerves, and getting specific feedback on pacing and filler words rather than general advice.',
 'active', '2025-01-05 09:00:00', '2026-09-02 09:00:00'),

(7, 'Database Design', 'database-design', 2,
 'Modeling data relationships and normalizing schemas for reliable, efficient systems.',
 'Covers modeling entities and relationships, normalization, and the trade-offs between a clean schema and a fast query - the part coursework often skips.',
 'active', '2025-01-05 09:00:00', '2026-09-09 09:00:00'),

(8, 'Arduino', 'arduino', 4,
 'Building and programming microcontroller projects, from sensors to simple robotics.',
 'Hands-on sessions with real boards and components - wiring, debouncing, sensors and the debugging habits that save the most time on a first project.',
 'active', '2025-01-05 09:00:00', '2026-08-22 09:00:00'),

(9, 'Academic Writing', 'academic-writing', 6,
 'Structuring essays, reports and citations for university-level coursework.',
 'Mentors help structure arguments, tighten paragraphs and get citations right for the specific style your department expects.',
 'active', '2025-01-05 09:00:00', '2026-08-15 09:00:00'),

(10, 'Digital Marketing', 'digital-marketing', 7,
 'Reaching an audience through social media, content and basic campaign analytics.',
 'Sessions cover the basics of reaching an audience - content planning, social platforms and reading enough analytics to know if something worked.',
 'active', '2025-01-05 09:00:00', '2026-08-12 09:00:00'),

(11, 'JavaScript', 'javascript', 1,
 'The core scripting language of the web, used alongside React for interactive interfaces.',
 NULL,
 'active', '2025-01-05 09:00:00', '2026-09-07 09:00:00'),

(12, 'Presentation Skills', 'presentation-skills', 5,
 'Turning a talk''s structure into a confident, well-paced delivery in front of an audience.',
 NULL,
 'active', '2025-01-05 09:00:00', '2026-09-03 09:00:00'),

(13, 'Machine Learning', 'machine-learning', 2,
 'Using data and Python to build models that recognize patterns and make predictions.',
 NULL,
 'active', '2025-01-05 09:00:00', '2026-09-04 09:00:00'),

(14, 'Embedded Systems', 'embedded-systems', 4,
 'Programming the hardware side of microcontroller projects - sensors, timing and low-level control.',
 NULL,
 'active', '2025-01-05 09:00:00', '2026-08-21 09:00:00');


-- =====================================================================
--  users
--
--  Column order:
--    id, full_name, initials, email, university_id, password_hash,
--    department_id, role, is_admin, year_of_study, headline, bio,
--    status, suspend_reason,
--    learning_points, mentor_points, avg_rating, total_reviews,
--    sessions_as_learner, sessions_as_mentor, learners_helped,
--    last_active_at, created_at
--
--  last_active_at converts the frontend's relative strings ("12 min ago",
--  "3 weeks ago") against a fixed anchor of 2026-09-14 10:00:00, which is
--  the effective "now" of the existing mock data.
--
--  Bios / headlines / years are only set where the frontend actually
--  establishes them (users 1, 2, 3, 4). The rest are NULL rather than
--  invented.
-- =====================================================================
INSERT INTO users
    (id, full_name, initials, email, university_id, password_hash,
     department_id, role, is_admin, year_of_study, headline, bio,
     status, suspend_reason,
     learning_points, mentor_points, avg_rating, total_reviews,
     sessions_as_learner, sessions_as_mentor, learners_helped,
     last_active_at, created_at)
VALUES

-- 1 — the demo account index.php currently signs in as (dual-role)
(1, 'Nabila Rahman', 'NR', 'nabila.rahman@university.edu', 'UKN-2026-0142', @pw,
 1, 'dual', 0, '3rd Year', NULL,
 'I''m a Computer Science student interested in Python, databases, and data analysis. I''m currently improving my backend and problem-solving skills.',
 'active', NULL,
 412, 520, 4.8, 42, 18, 27, 0,
 '2026-09-14 09:48:00', '2026-01-12 09:00:00'),

-- 2 — the mentor every page links to (mentor-profile&id=2)
(2, 'Rahim Ahmed', 'RA', 'rahim.ahmed@university.edu', 'UKN-2025-0874', @pw,
 1, 'mentor', 0, '4th Year', 'Python & Data Analysis Mentor',
 'I help students learn Python, database design and practical data analysis through project-based sessions.',
 'active', NULL,
 0, 520, 4.9, 42, 0, 127, 84,
 '2026-09-14 08:00:00', '2025-09-18 09:00:00'),

-- 3
(3, 'Imran Chowdhury', 'IC', 'imran.chowdhury@university.edu', 'UKN-2026-0201', @pw,
 4, 'learner', 0, '2nd Year', NULL,
 'Second-year English student working on academic presentation skills for seminars and case competitions. Learning by doing, not just reading about it.',
 'active', NULL,
 318, 0, NULL, 0, 14, 0, 0,
 '2026-09-13 10:00:00', '2026-02-03 09:00:00'),

-- 4
(4, 'Hasan Mahmud', 'HM', 'hasan.mahmud@university.edu', 'UKN-2025-0653', @pw,
 2, 'mentor', 0, '4th Year', 'Arduino & Embedded Systems Mentor',
 'I mentor students building their first Arduino projects, focusing on wiring, debouncing and practical debugging over pure theory.',
 'active', NULL,
 0, 365, 4.7, 21, 0, 52, 38,
 '2026-09-14 07:00:00', '2025-08-05 09:00:00'),

-- 5 — second dual-role account (learns UI/UX, teaches React)
(5, 'Ayesha Rahman', 'AR', 'ayesha.rahman@university.edu', 'UKN-2025-0961', @pw,
 1, 'dual', 0, NULL, NULL, NULL,
 'active', NULL,
 184, 368, 4.7, 0, 7, 71, 46,
 '2026-09-14 09:20:00', '2025-10-22 09:00:00'),

-- 6
(6, 'Sara Khan', 'SK', 'sara.khan@university.edu', 'UKN-2025-0512', @pw,
 3, 'mentor', 0, NULL, NULL, NULL,
 'active', NULL,
 0, 410, 4.8, 0, 0, 84, 55,
 '2026-09-14 05:00:00', '2025-06-14 09:00:00'),

-- 7
(7, 'Farhan Kabir', 'FK', 'farhan.kabir@university.edu', 'UKN-2025-0388', @pw,
 1, 'mentor', 0, NULL, NULL, NULL,
 'active', NULL,
 0, 462, 4.9, 0, 0, 103, 67,
 '2026-09-14 09:40:00', '2025-04-02 09:00:00'),

-- 8
(8, 'Nusrat Jahan', 'NJ', 'nusrat.jahan@university.edu', 'UKN-2025-1102', @pw,
 4, 'mentor', 0, NULL, NULL, NULL,
 'active', NULL,
 0, 240, 4.6, 0, 0, 28, 21,
 '2026-09-13 10:00:00', '2025-12-09 09:00:00'),

-- 9
(9, 'Mahi Noor', 'MN', 'mahi.noor@university.edu', 'UKN-2026-0057', @pw,
 1, 'learner', 0, NULL, NULL, NULL,
 'active', NULL,
 356, 0, NULL, 0, 16, 0, 0,
 '2026-09-14 08:00:00', '2026-03-30 09:00:00'),

-- 10
(10, 'Tanvir Hossain', 'TH', 'tanvir.hossain@university.edu', 'UKN-2026-0089', @pw,
 2, 'learner', 0, NULL, NULL, NULL,
 'active', NULL,
 331, 0, NULL, 0, 15, 0, 0,
 '2026-09-14 04:00:00', '2026-02-18 09:00:00'),

-- 11
(11, 'Sabrina Ali', 'SA', 'sabrina.ali@university.edu', 'UKN-2026-0333', @pw,
 4, 'learner', 0, NULL, NULL, NULL,
 'active', NULL,
 264, 0, NULL, 0, 12, 0, 0,
 '2026-09-11 10:00:00', '2026-05-27 09:00:00'),

-- 12
(12, 'Adil Hasan', 'AH', 'adil.hasan@university.edu', 'UKN-2026-0410', @pw,
 2, 'learner', 0, NULL, NULL, NULL,
 'active', NULL,
 241, 0, NULL, 0, 10, 0, 0,
 '2026-09-10 10:00:00', '2026-07-09 09:00:00'),

-- 13 — inactive account, for the admin status filter
(13, 'Maliha Islam', 'MI', 'maliha.islam@university.edu', 'UKN-2026-0475', @pw,
 3, 'learner', 0, NULL, NULL, NULL,
 'inactive', NULL,
 309, 0, NULL, 0, 14, 0, 0,
 '2026-08-24 10:00:00', '2026-04-21 09:00:00'),

-- 14 — brand-new account, for admin "Recent Users"
(14, 'Tanjim Rahman', 'TR', 'tanjim.rahman@university.edu', 'UKN-2026-0512', @pw,
 3, 'learner', 0, NULL, NULL, NULL,
 'active', NULL,
 45, 0, NULL, 0, 1, 0, 0,
 '2026-09-14 09:42:00', '2026-09-13 09:00:00'),

-- 15 — suspended mentor, exercises chk_users_suspend_reason
(15, 'Kamrul Hasan', 'KH', 'kamrul.hasan@university.edu', 'UKN-2026-0498', @pw,
 2, 'mentor', 0, NULL, NULL, NULL,
 'suspended', 'Policy violation',
 0, 60, 3.9, 0, 0, 4, 3,
 '2026-09-12 10:00:00', '2026-09-12 09:00:00'),

-- 16 — suspended learner
(16, 'Farhana Islam', 'FI', 'farhana.islam@university.edu', 'UKN-2026-0501', @pw,
 4, 'learner', 0, NULL, NULL, NULL,
 'suspended', 'Spam',
 20, 0, NULL, 0, 1, 0, 0,
 '2026-09-09 10:00:00', '2026-09-13 09:00:00'),

-- 17 — the admin panel's "Admin User" (admin/includes/header.php).
--      is_admin = 1 is what gates admin/*.php; the role ENUM has no
--      'admin' value on purpose, matching the frontend's own separation.
(17, 'Admin User', 'AU', 'admin@university.edu', 'UKN-ADMIN-0001', @pw,
 NULL, 'learner', 1, NULL, NULL, NULL,
 'active', NULL,
 0, 0, NULL, 0, 0, 0, 0,
 '2026-09-14 09:00:00', '2025-01-05 09:00:00');


-- =====================================================================
--  Default settings row for every seeded user.
--  Included because user_settings.user_id is NOT NULL and the Settings
--  page expects a row to exist — not because it was requested as demo
--  data in its own right.
-- =====================================================================
INSERT INTO user_settings (user_id)
SELECT id FROM users;


COMMIT;


-- =====================================================================
--  Sanity checks — expected: 7 / 7 / 14 / 17 / 17
-- =====================================================================
SELECT 'departments'      AS table_name, COUNT(*) AS rows_seeded FROM departments
UNION ALL SELECT 'skill_categories', COUNT(*) FROM skill_categories
UNION ALL SELECT 'skills',           COUNT(*) FROM skills
UNION ALL SELECT 'users',            COUNT(*) FROM users
UNION ALL SELECT 'user_settings',    COUNT(*) FROM user_settings;

-- Every skill resolves to a category:
SELECT c.name AS category, COUNT(s.id) AS skill_count
FROM skill_categories c
LEFT JOIN skills s ON s.category_id = c.id
GROUP BY c.id, c.name
ORDER BY skill_count DESC, c.name;

-- Users per department + role, as admin/users.php renders it:
SELECT COALESCE(d.name, '(none)') AS department, u.role, COUNT(*) AS users
FROM users u
LEFT JOIN departments d ON d.id = u.department_id
GROUP BY d.name, u.role
ORDER BY department, u.role;
